/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tabgroups.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "swallow.h"
/* Layouts */
#include "layout_fibonacci.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

